import styled from 'styled-components';
export const projects = [
  // {
  //   title: 'Microsoft Packages',
  //     description: "Highly proficient in Microsoft packages, with extensive hands-on experience and unwavering dedication to staying updated. I possess a deep understanding and mastery of diverse functionalities, enhancing software utilization.",  
  //   // description: "Proficiently skilled in the comprehensive suite of Microsoft packages, encompassing an extensive range of software tools and applications. With a wealth of hands-on experience and an unwavering dedication to staying up-to-date with the latest advancements, I have developed a deep understanding and mastery of the diverse functionalities and capabilities offered by Microsoft's software offerings.",
  //     image: '/images/mp1.png',
  //     tags: ['Excel', 'Powerpoint', 'Word'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 0,
  // },
  // {
  //   title: 'System Administrator',
  //   description:"With extensive system administration expertise and a passion for optimizing computer systems, I possess hands-on experience in installing, configuring, and maintaining operating systems for seamless functionality and robust security.",
  //   image: '/images/2.png',
  //   tags: ['Microsoft Windows', 'MacOS', 'Linux in all Distros'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 1,
  // },
  // {
  //   title: 'Colaboration',
  //   description: "my proficiency in problem-solving, critical thinking, teamwork, and innovation empowers me to navigate complexities with agility, devise optimal solutions, collaborate effectively, and continuously push the boundaries of what is possible. These skills form the cornerstone of my approach, enabling me to deliver exceptional results and make a meaningful impact in any endeavor I undertake.",
  //     image: '/images/3.jpg',
  //     tags: ['React', 'WebRTC'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 2,
  // },
  {
    title: 'Microsoft Packages',
    description: "Skilled in Microsoft packages, with hands-on experience and dedication to staying updated. Deep understanding and mastery for enhanced software utilization.",
    image: '/images/My project (6).png',
    tags: ['Excel', 'Power Point', 'Word'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'System Administrator',
    description: "Passionate system admin with extensive expertise in optimizing computer systems. Hands-on experience in installing, configuring, and maintaining OS for seamless functionality and robust security",
    image: '/images/My project (10).png',
  tags: ['Microsoft Windows', 'MacOS', 'Linux in all Distros'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Web Development',
    // description: "Proficient in problem-solving, critical thinking, teamwork, and innovation, enabling agile navigation of complexities and delivery of exceptional results with a meaningful impact",
    description: "I excel in crafting scalable websites using cutting-edge tech, hands-on expertise, load balancing, cloud integration, and continuous optimization.",
    image: '/images/My project (7).png',
    tags: ['HTML 5', 'CSS 3', 'Node Js'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Coding Versatilty',
    description: "Proficient in multiple programming languages, enabling efficient and creative development of software solutions and problem-solving.",
    image: '/images/My project (8).png',
    tags: ['C++', 'Java', 'Python',],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  }
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];